spring:
  cache:
    type: redis
  redis:
    host: 10.191.10.3
    port: 6379
    database: 0
  data:
    mongodb:
      uri: mongodb+srv://root:elpreciomasbajo@clustertest.kcun4.mongodb.net/util?authSource=admin&retryWrites=true&w=majority&maxPoolSize=2500&maxIdleTimeMS=20000
  cloud:
    gcp:
      project-id: fp-ci-poc
      credentials:
        location: classpath:gcp/qa/fp-serverless-qa-project-84aa081dd49c.json
    stream:
      bindings:
        channel_event_1:
          destination: event.atlasmongo.topic
          group: redis.sub
